//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoProfiler.Demos.SimpleDemo.DemoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DemoService.IWcfDemoService")]
    public interface IWcfDemoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDemoService/DoWork", ReplyAction="http://tempuri.org/IWcfDemoService/DoWorkResponse")]
        void DoWork(string p1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDemoService/DoWork", ReplyAction="http://tempuri.org/IWcfDemoService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync(string p1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfDemoServiceChannel : NanoProfiler.Demos.SimpleDemo.DemoService.IWcfDemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfDemoServiceClient : System.ServiceModel.ClientBase<NanoProfiler.Demos.SimpleDemo.DemoService.IWcfDemoService>, NanoProfiler.Demos.SimpleDemo.DemoService.IWcfDemoService {
        
        public WcfDemoServiceClient() {
        }
        
        public WcfDemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfDemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfDemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfDemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork(string p1) {
            base.Channel.DoWork(p1);
        }
        
        public System.Threading.Tasks.Task DoWorkAsync(string p1) {
            return base.Channel.DoWorkAsync(p1);
        }
    }
}
